-- Privileges for each role inside one environment's database.
-- {{ database }} = DEV_DB / TEST_DB / PROD_DB,  {{ env }} = DEV / TEST / PROD

USE ROLE SYSADMIN;
USE DATABASE {{ database }};

-- 1. Every role can see the database
GRANT USAGE ON DATABASE {{ database }} TO ROLE {{ env }}_ENGINEER;
GRANT USAGE ON DATABASE {{ database }} TO ROLE {{ env }}_LOADER;
GRANT USAGE ON DATABASE {{ database }} TO ROLE {{ env }}_TRANSFORMER;
{% if env != 'DEV' %}
GRANT USAGE ON DATABASE {{ database }} TO ROLE {{ env }}_ANALYST;
{% endif %}

-- 2. LOADER: read and write RAW and AUDIT, use UTIL
GRANT USAGE ON SCHEMA RAW TO ROLE {{ env }}_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES    IN SCHEMA RAW TO ROLE {{ env }}_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA RAW TO ROLE {{ env }}_LOADER;
GRANT USAGE ON FUTURE STAGES       IN SCHEMA RAW TO ROLE {{ env }}_LOADER;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA RAW TO ROLE {{ env }}_LOADER;
GRANT OPERATE, MONITOR ON FUTURE PIPES IN SCHEMA RAW TO ROLE {{ env }}_LOADER;

GRANT USAGE ON SCHEMA AUDIT TO ROLE {{ env }}_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES    IN SCHEMA AUDIT TO ROLE {{ env }}_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA AUDIT TO ROLE {{ env }}_LOADER;

GRANT USAGE ON SCHEMA UTIL TO ROLE {{ env }}_LOADER;
GRANT USAGE ON FUTURE FUNCTIONS  IN SCHEMA UTIL TO ROLE {{ env }}_LOADER;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA UTIL TO ROLE {{ env }}_LOADER;

-- 3. TRANSFORMER: read RAW and AUDIT, use UTIL, create its own schemas
GRANT USAGE ON SCHEMA RAW TO ROLE {{ env }}_TRANSFORMER;
GRANT SELECT ON ALL TABLES    IN SCHEMA RAW TO ROLE {{ env }}_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW TO ROLE {{ env }}_TRANSFORMER;

GRANT USAGE ON SCHEMA AUDIT TO ROLE {{ env }}_TRANSFORMER;
GRANT SELECT ON ALL TABLES    IN SCHEMA AUDIT TO ROLE {{ env }}_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AUDIT TO ROLE {{ env }}_TRANSFORMER;

GRANT USAGE ON SCHEMA UTIL TO ROLE {{ env }}_TRANSFORMER;
GRANT USAGE ON FUTURE FUNCTIONS  IN SCHEMA UTIL TO ROLE {{ env }}_TRANSFORMER;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA UTIL TO ROLE {{ env }}_TRANSFORMER;

GRANT CREATE SCHEMA ON DATABASE {{ database }} TO ROLE {{ env }}_TRANSFORMER;

-- 4. ENGINEER
{% if env == 'DEV' %}
-- DEV: engineer gets everything LOADER and TRANSFORMER have
USE ROLE SECURITYADMIN;
GRANT ROLE DEV_LOADER      TO ROLE DEV_ENGINEER;
GRANT ROLE DEV_TRANSFORMER TO ROLE DEV_ENGINEER;
{% else %}
-- TEST / PROD: engineer can only read RAW and AUDIT
GRANT USAGE ON SCHEMA RAW TO ROLE {{ env }}_ENGINEER;
GRANT SELECT ON ALL TABLES    IN SCHEMA RAW TO ROLE {{ env }}_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW TO ROLE {{ env }}_ENGINEER;
GRANT USAGE ON SCHEMA AUDIT TO ROLE {{ env }}_ENGINEER;
GRANT SELECT ON ALL TABLES    IN SCHEMA AUDIT TO ROLE {{ env }}_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AUDIT TO ROLE {{ env }}_ENGINEER;
{% endif %}