-- Roles and users. Privileges are given to roles in migrations/environment.

USE ROLE USERADMIN;

-- 1. Roles
CREATE ROLE IF NOT EXISTS DEV_ENGINEER;
CREATE ROLE IF NOT EXISTS DEV_LOADER;
CREATE ROLE IF NOT EXISTS DEV_TRANSFORMER;

CREATE ROLE IF NOT EXISTS TEST_ENGINEER;
CREATE ROLE IF NOT EXISTS TEST_LOADER;
CREATE ROLE IF NOT EXISTS TEST_TRANSFORMER;
CREATE ROLE IF NOT EXISTS TEST_ANALYST;

CREATE ROLE IF NOT EXISTS PROD_ENGINEER;
CREATE ROLE IF NOT EXISTS PROD_LOADER;
CREATE ROLE IF NOT EXISTS PROD_TRANSFORMER;
CREATE ROLE IF NOT EXISTS PROD_ANALYST;

-- 2. Users for programs
CREATE USER IF NOT EXISTS SVC_DBT_TEST    TYPE = SERVICE DEFAULT_ROLE = TEST_TRANSFORMER;
CREATE USER IF NOT EXISTS SVC_DBT_PROD    TYPE = SERVICE DEFAULT_ROLE = PROD_TRANSFORMER;
CREATE USER IF NOT EXISTS SVC_LOADER_TEST TYPE = SERVICE DEFAULT_ROLE = TEST_LOADER;
CREATE USER IF NOT EXISTS SVC_LOADER_PROD TYPE = SERVICE DEFAULT_ROLE = PROD_LOADER;
CREATE USER IF NOT EXISTS SVC_CI_DEV      TYPE = SERVICE DEFAULT_ROLE = DEV_TRANSFORMER;

USE ROLE SECURITYADMIN;

-- 3. Give every role to SYSADMIN, so the admin can see and fix anything these roles create
GRANT ROLE DEV_ENGINEER     TO ROLE SYSADMIN;
GRANT ROLE DEV_LOADER       TO ROLE SYSADMIN;
GRANT ROLE DEV_TRANSFORMER  TO ROLE SYSADMIN;
GRANT ROLE TEST_ENGINEER    TO ROLE SYSADMIN;
GRANT ROLE TEST_LOADER      TO ROLE SYSADMIN;
GRANT ROLE TEST_TRANSFORMER TO ROLE SYSADMIN;
GRANT ROLE TEST_ANALYST     TO ROLE SYSADMIN;
GRANT ROLE PROD_ENGINEER    TO ROLE SYSADMIN;
GRANT ROLE PROD_LOADER      TO ROLE SYSADMIN;
GRANT ROLE PROD_TRANSFORMER TO ROLE SYSADMIN;
GRANT ROLE PROD_ANALYST     TO ROLE SYSADMIN;

-- 4. Give each program user its role
GRANT ROLE TEST_TRANSFORMER TO USER SVC_DBT_TEST;
GRANT ROLE PROD_TRANSFORMER TO USER SVC_DBT_PROD;
GRANT ROLE TEST_LOADER      TO USER SVC_LOADER_TEST;
GRANT ROLE PROD_LOADER      TO USER SVC_LOADER_PROD;
GRANT ROLE DEV_TRANSFORMER  TO USER SVC_CI_DEV;