-- One warehouse per environment, each with a credit budget (resource monitor).

-- 1. Warehouses
USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS DEV_WH
  WAREHOUSE_SIZE = XSMALL  AUTO_SUSPEND = 60  AUTO_RESUME = TRUE  INITIALLY_SUSPENDED = TRUE
  STATEMENT_TIMEOUT_IN_SECONDS = 3600
  COMMENT = 'DEV compute';

CREATE WAREHOUSE IF NOT EXISTS TEST_WH
  WAREHOUSE_SIZE = XSMALL  AUTO_SUSPEND = 60  AUTO_RESUME = TRUE  INITIALLY_SUSPENDED = TRUE
  STATEMENT_TIMEOUT_IN_SECONDS = 3600
  COMMENT = 'TEST compute';

CREATE WAREHOUSE IF NOT EXISTS PROD_WH
  WAREHOUSE_SIZE = XSMALL  AUTO_SUSPEND = 60  AUTO_RESUME = TRUE  INITIALLY_SUSPENDED = TRUE
  STATEMENT_TIMEOUT_IN_SECONDS = 3600
  COMMENT = 'PROD compute';

-- 2. Resource monitors (only ACCOUNTADMIN can create them)
USE ROLE ACCOUNTADMIN;

CREATE RESOURCE MONITOR IF NOT EXISTS DEV_RM
  WITH CREDIT_QUOTA = 10 FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
  TRIGGERS ON 75 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND
           ON 110 PERCENT DO SUSPEND_IMMEDIATE;

CREATE RESOURCE MONITOR IF NOT EXISTS TEST_RM
  WITH CREDIT_QUOTA = 5 FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
  TRIGGERS ON 75 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND
           ON 110 PERCENT DO SUSPEND_IMMEDIATE;

CREATE RESOURCE MONITOR IF NOT EXISTS PROD_RM
  WITH CREDIT_QUOTA = 15 FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
  TRIGGERS ON 75 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND
           ON 110 PERCENT DO SUSPEND_IMMEDIATE;

CREATE RESOURCE MONITOR IF NOT EXISTS ACCOUNT_RM
  WITH CREDIT_QUOTA = 40 FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
  TRIGGERS ON 50 PERCENT DO NOTIFY
           ON 75 PERCENT DO NOTIFY
           ON 90 PERCENT DO NOTIFY;

ALTER WAREHOUSE DEV_WH  SET RESOURCE_MONITOR = DEV_RM;
ALTER WAREHOUSE TEST_WH SET RESOURCE_MONITOR = TEST_RM;
ALTER WAREHOUSE PROD_WH SET RESOURCE_MONITOR = PROD_RM;
ALTER ACCOUNT SET RESOURCE_MONITOR = ACCOUNT_RM;

-- 3. Privileges: each environment's roles may use only their own warehouse
USE ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE DEV_WH TO ROLE DEV_ENGINEER;
GRANT USAGE ON WAREHOUSE DEV_WH TO ROLE DEV_LOADER;
GRANT USAGE ON WAREHOUSE DEV_WH TO ROLE DEV_TRANSFORMER;

GRANT USAGE ON WAREHOUSE TEST_WH TO ROLE TEST_ENGINEER;
GRANT USAGE ON WAREHOUSE TEST_WH TO ROLE TEST_LOADER;
GRANT USAGE ON WAREHOUSE TEST_WH TO ROLE TEST_TRANSFORMER;
GRANT USAGE ON WAREHOUSE TEST_WH TO ROLE TEST_ANALYST;

GRANT USAGE ON WAREHOUSE PROD_WH TO ROLE PROD_ENGINEER;
GRANT USAGE ON WAREHOUSE PROD_WH TO ROLE PROD_LOADER;
GRANT USAGE ON WAREHOUSE PROD_WH TO ROLE PROD_TRANSFORMER;
GRANT USAGE ON WAREHOUSE PROD_WH TO ROLE PROD_ANALYST;

-- 4. Default warehouse for each program user
USE ROLE USERADMIN;

ALTER USER SVC_DBT_TEST    SET DEFAULT_WAREHOUSE = TEST_WH;
ALTER USER SVC_DBT_PROD    SET DEFAULT_WAREHOUSE = PROD_WH;
ALTER USER SVC_LOADER_TEST SET DEFAULT_WAREHOUSE = TEST_WH;
ALTER USER SVC_LOADER_PROD SET DEFAULT_WAREHOUSE = PROD_WH;
ALTER USER SVC_CI_DEV      SET DEFAULT_WAREHOUSE = DEV_WH;